# -*- coding: utf-8 -*-


"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n5t-964KR5m16ftPu1pEPSpIrZ5EY00n
"""

#pip install streamlit
import streamlit as st

# --- STYLING TO MATCH YOUR PROTOTYPE ---
st.markdown("""
    <style>
    .main { background-color: #f5f7f9; }
    /* Add your other styles here */
    </style>
    """, unsafe_allow_html=True)

st.title("🐔 AgriAlert Mbour")

# --- MBOUR DATA INPUT (Necessary metrics only) ---
# Focusing on the critical data from TimeAndDate: Temp and Humidity
with st.container():
    st.markdown('<div class="alert-card">', unsafe_allow_index=True)
    temp = st.number_input("Current Mbour Temperature (°C)", value=32)
    humidity = st.number_input("Humidity (%)", value=75)
    
    # Simple predictive logic for Mbour's specific heat stress
    stress_index = temp + (0.55 * humidity)
    
    if st.button("RUN PREDICTION"):
        if stress_index > 70:
            st.error("🚨 CRITICAL: Heat Stress Detected in Mbour")
            st.warning("Action: Sending SMS alerts to poultry farmers...")
            # This is where your SMS/Call logic connects
        else:
            st.success("✅ STABLE: Conditions are safe for poultry.")
    st.markdown('</div>', unsafe_allow_index=True)



